<a href="https://colab.research.google.com/github/nileshgarg-tech/mortgage-ai-document-intelligence/blob/main/Introduction_to_Pandas_Beginner's_Guide_Car_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

Pandas is an open source python library which contains data structures and data manipulation tools designed to make data cleaning and analysis fast and convenient in python.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008. It introduces two fundamental data structures: Series and DataFrame, which allow data to be organized, manipulated, and analyzed in a tabular format similar to spreadsheets or databases.

<b><u>Reasons why Datascience professionals are highly dependent on Pandas.</u></b>

1. Pandas simplifies the process of data handling and manipulation, allowing its users to clean, preprocess, and transform data.
2. It offers powerful tools for data analysis and exploration.
3. It provides functions for aggregating data, computing descriptive statistics, handling time series data, and working with categorical and textual data.
4. It excels at data integration and preparation. We can easily load data from different sources (such as CSV, Excel, SQL databases, and more), merge or join datasets, and perform data transformations before further analysis.

<h4>Installation</h4>

To install Pandas, you can execute the command mentioned below in your terminal or command prompt:

In [3]:
#!pip install pandas

### What do we learn in this segment?

Pandas is very vast and there is so much more to explore. But as a beginner, in order to understand the essence of this library, one needs to atleast practice the following steps and these will be covered in this segment.

1. Import Pandas library
2. Data types
3. Reading and writing Data
4. Data Exploration and cleaning
5. Data Manipulation
6. Data aggregation and grouping

<h3>1. Import pandas library</h3>

The initial step is to import the pandas library in order to use its functions. Normally pandas will be referred as pd (abbreviated form)

In [4]:
import pandas as pd

Now that we have imported the pandas library and henceforth it will be referred as pd. Lets move on to its datatypes.

<h3>2. Data types</h3>

* Pandas series - which is a one-dimensional data
* Pandas Dataframe - which is a two-dimensional dataset

you can create a Series using pd.Series() and passing it a Python list.

In [5]:
colors = pd.Series(['Blue', 'Red', 'Orange','Yellow'])
colors

0      Blue
1       Red
2    Orange
3    Yellow
dtype: object

In [6]:
bikes = pd.Series(['Yamaha','Honda','TVS','Vespa'])
bikes

0    Yamaha
1     Honda
2       TVS
3     Vespa
dtype: object

Let us use the above mentioned Series objects to create a DataFrame.

In [7]:
vehicle_df = pd.DataFrame({"Vehicle type": bikes,
                         "Color spec": colors})
vehicle_df

  Vehicle type Color spec
0       Yamaha       Blue
1        Honda        Red
2          TVS     Orange
3        Vespa     Yellow

Now let us explore few of the built-in function in the dataframe object.

In [8]:
#prints the datatypes of the columns present in the dataframe.
#Note : column with any datatype can be added to the dataframe.
vehicle_df.dtypes

Vehicle type    object
Color spec      object
dtype: object

In [9]:
#Displays the colulmns present in the dataframe.
vehicle_df.columns

Index(['Vehicle type', 'Color spec'], dtype='object')

One can access the cars dataset from Kaggle's website using the following link

[Used Car Price Prediction Dataset](https://www.kaggle.com/datasets/taeefnajib/used-car-price-prediction-dataset)

So now we have learnt to create a series and dataframe object.

<h3>Reading Data</h3>

Now lets see how to import data from a csv or excel file and perform further operations.

1. To read a csv file, we should use read_csv option in pandas.
2. To read an excel file, read_excel option should be used.

Note:
The csv file given here is being downloaded from "Kaggle" website.

In [27]:
car_data = pd.read_csv("/content/used_cars.csv")
car_data

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"
...,...,...,...,...,...,...,...,...,...,...,...,...
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

<h3>3. Data Exploration and Cleaning</h3>

One of the first things you'll want to do after you import some data into a pandas DataFrame is to start exploring it.

Data cleaning deals with handing missing values

pandas has many built in functions which allow you to quickly get information about a DataFrame.

Let's explore some using the car_sales DataFrame.

In [28]:
#Displays the first 5 columns
car_data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [29]:
#Upon mentioning the number columns to be displayed, this head method will retieve the given count of rows.
car_data.head(10)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"
5,Acura,ILX 2.4L,2016,"136,397 mi.",Gasoline,2.4 Liter,F,Silver,Ebony.,None reported,NaN,"$14,798"
6,Audi,S3 2.0T Premium Plus,2017,"84,000 mi.",Gasoline,292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Blue,Black,None reported,Yes,"$31,000"
7,BMW,740 iL,2001,"242,000 mi.",Gasoline,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Green,Green,None reported,Yes,"$7,300"
8,Lexus,RC 350 F Sport,2021,"23,436 mi.",Gasoline,311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,"$41,927"
9,Tesla,Model X Long Range Plus,2020,"34,000 mi.",NaN,534.0HP Electric Motor Electric Fuel System,A/T,Black,Black,None reported,Yes,"$69,950"

In [30]:
#Likewise, we can see the last 5 records with the below given function
car_data.tail()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
4004,Bentley,Continental GT Speed,2023,714 mi.,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,"$349,950"
4005,Audi,S4 3.0T Premium Plus,2022,"10,900 mi.",Gasoline,349.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$53,900"
4006,Porsche,Taycan,2022,"2,116 mi.",NaN,Electric,Automatic,Black,Black,None reported,NaN,"$90,998"
4007,Ford,F-150 Raptor,2020,"33,000 mi.",Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,None reported,Yes,"$62,999"
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [31]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   object
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   object
dtypes: int64(1), object(11)
memory usage: 376.0+ KB

Info() will display the brief summary of the dataframe such as no of rows, total number of columns, datatype, column type(NULL o Non-NULL), memory usage per column. This will help in assessing the overall structure of the dataframe.

In [32]:
# Returns the dimensions of the dataframe
car_data.shape

(4009, 12)

This dataframe contains 4009 rows and 12 columns.

In [33]:
#Gives the data type of each columns
car_data.dtypes

brand           object
model           object
model_year       int64
milage          object
fuel_type       object
engine          object
transmission    object
ext_col         object
int_col         object
accident        object
clean_title     object
price           object
dtype: object

First, I'll clean the 'milage' and 'price' columns by removing non-numeric characters like ' mi.', ',', and '$'. Then, I'll convert them to a float data type.

In [34]:
# Remove ' mi.', '$', and commas, then convert to float
car_data['milage'] = car_data['milage'].str.replace(' mi.', '', regex=False).str.replace(',', '', regex=False).astype(float)
car_data['price'] = car_data['price'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

# Verify types and data
print(car_data.dtypes)
display(car_data[['milage', 'price']].head())

brand            object
model            object
model_year        int64
milage          float64
fuel_type        object
engine           object
transmission     object
ext_col          object
int_col          object
accident         object
clean_title      object
price           float64
dtype: object

    milage    price
0  51000.0  10300.0
1  34742.0  38005.0
2  22372.0  54598.0
3  88900.0  15500.0
4   9835.0  34999.0

In [35]:
#Detects the sum of all null values prsent in the dataframe.
car_data.isna().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

So we have found out how much na or null values are present in the dataframe. Now its time to handle these null values.
We can either fill the values with suitable alternate values or drop the null values.
This can be achieved with the following functions.
1. fillna() - Fill the null values with suitable alternate values. (0 or mean of the column)
2. dropna() - drop the null values.

The decision to fill or drop should taken wisely considering the usage of the column and the contribution of it to the dataset. If the colulmn containing null values is the most important one and if the insights are derived from that particular column, then it would be better choice to drop the value. Because, whatever data we fill will be based on our assumption, it won't be accurate. So it is better to derive proper insight with right data even if it is available in less number.

In [36]:
#Now we will drop the null values in the car data dataframe

car_data = car_data.dropna()

car_data.isna().sum()

brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

After dropping the null values, the dataset now has 0 null values.

The Describe function provides a quick statistical overview of the numerical columns present in the Data Frame.

In [37]:
car_data.describe()

        model_year         milage         price
count  3269.000000    3269.000000  3.269000e+03
mean   2014.601407   72126.951973  4.124113e+04
std       6.152181   53387.413623  8.304604e+04
min    1974.000000     100.000000  2.000000e+03
25%    2011.000000   30450.000000  1.550000e+04
50%    2016.000000   62930.000000  2.800000e+04
75%    2019.000000  102750.000000  4.650000e+04
max    2024.000000  405000.000000  2.954083e+06

* Count - Gives the number of non-null values
* mean - The average of the values present in the column
* std - Standard deviation value for the data present in the column
* min - minimum value present in the given column
* max - maximum value present in the given column
* 25% - 25 percentile (the value at which 25% of the answers lie below that value and 75% of the answers lie above that value.)
* 50% - 50 percentile (Also known as the Median. The median cuts the data set in half.  Half of the answers lie below the median and half lie above the median.)
* 75% - 75 percentile (Also known as the third, or upper, quartile. The 75th percentile is the value at which 25% of the answers lie above that value and 75% of the answers lie below that value. Above the 75th or below the 25th percentile)

<h3>4. Data Manipulation</h3>

 Perform filtering, sorting, and selection operations on the data comes under data manipulation.
 Through this we will be able to understand the pattern of the data to some extent.  data).

In [39]:
#Filtering rows based on selling price greater than 100k USD
filtered_data = car_data[car_data['price'] > 100000]
filtered_data

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
11,Aston,Martin DBS Superleggera,2019,22770.0,Gasoline,715.0HP 5.2L 12 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes,184606.0
16,Mercedes-Benz,Metris Base,2021,1685.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,9-Speed Automatic,Gray,White,None reported,Yes,250000.0
71,Bentley,Continental GT W12,2017,14684.0,Gasoline,582.0HP 6.0L 12 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,White,None reported,Yes,130000.0
93,Aston,Martin DBS Superleggera,2021,2165.0,Gasoline,5.2L V12 48V GDI DOHC Twin Turbo,8-Speed Automatic,Black,Black,None reported,Yes,279950.0
152,Ferrari,FF Base,2016,19987.0,Gasoline,651.0HP 6.3L 12 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Brown,None reported,Yes,149900.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3878,Lamborghini,Huracan LP610-4,2015,34152.0,Gasoline,602.0HP 5.2L 10 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,Red,None reported,Yes,185500.0
3959,Chevrolet,Corvette Stingray w/2LT,2023,2058.0,Gasoline,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes,101999.0
3964,Porsche,911 Carrera,2022,2950.0,Gasoline,379.0HP 3.0L Flat 6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Green,Black,None reported,Yes,131000.0
4002,Mercedes-Benz,AMG GLS 63 4MATIC,2023,2000.0,Hybrid,603.0HP 4.0L 8 Cylinder Engine Gasoline/Mild E...,9-Speed A/T,Gray,Beige,None reported,Yes,175000.0
4004,Bentley,Continental GT Speed,2023,714.0,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic with Auto-Shift,C / C,Hotspur,None reported,Yes,349950.0

In [41]:
#sorting based on Model Year
sorted_data = car_data.sort_values(by='model_year', ascending=True)
sorted_data

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
855,Ford,Bronco,1974,6217.0,–,–,–,Dark Gray Metallic,–,None reported,Yes,115000.0
1088,Mazda,MX-5 Miata Base,1992,125800.0,–,–,5-Speed M/T,Red,Black,None reported,Yes,11500.0
257,Toyota,Land Cruiser Base,1993,231500.0,–,–,A/T,White,Gray,None reported,Yes,29500.0
3469,Ford,F-250 XL SuperCab H/D,1993,115000.0,–,–,A/T,Red,Gray,None reported,Yes,21900.0
3922,Mazda,Protege DX,1993,94200.0,–,–,A/T,Gray,–,At least 1 accident or damage reported,Yes,2500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3309,GMC,Sierra 2500 Denali,2024,2043.0,Gasoline,401.0HP 6.6L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,White,Black,None reported,Yes,81500.0
556,Mazda,CX-90 Premium,2024,3880.0,Gasoline,2.5L,8-Speed Automatic,Machine Gray Metallic,Black,None reported,Yes,52991.0
443,BMW,M3 CS,2024,456.0,Gasoline,543.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,128995.0
3529,Lexus,NX 350h Premium,2024,300.0,Hybrid,240.0HP 2.5L 4 Cylinder Engine Gas/Electric Hy...,A/T,Black,Black,None reported,Yes,50999.0
1691,BMW,M3 CS,2024,124.0,Gasoline,543.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Green,Black,None reported,Yes,145000.0

<h3>5. Data Aggregation and Grouping</h3>

  Aggregate data using functions like sum, mean, count, etc., and perform grouping operation.

In [43]:
#Find the sum of all the values present in the sellingprice column
print(f"{car_data['price'].sum()} dollars ")

134817242.0 dollars

In [45]:
#find the mean, median and mode of the sellingprice column
print(f"{car_data['price'].mean()} dollars ")

41241.12633832976 dollars

In [46]:
#find the count of the rows for which the selling price is greater than 100000
car_count = car_data[car_data['price'] > 100000].count()
print(car_count)

brand           160
model           160
model_year      160
milage          160
fuel_type       160
engine          160
transmission    160
ext_col         160
int_col         160
accident        160
clean_title     160
price           160
dtype: int64

In [47]:
#groupby the data based on the model.
grouped_data = car_data.groupby('brand')
grouped_data.first()

,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
brand,,,,,,,,,,,
Acura,RL Technology,2010,97700.0,Gasoline,300.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Blue,Beige,None reported,Yes,10995.0
Alfa,Romeo Stelvio Ti Sport,2020,18665.0,Gasoline,2.0L I4 16V GDI SOHC Turbo,8-Speed Automatic,Lunare White Metallic,Ice,None reported,Yes,35645.0
Aston,Martin DBS Superleggera,2019,22770.0,Gasoline,715.0HP 5.2L 12 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes,184606.0
Audi,S3 2.0T Premium Plus,2017,84000.0,Gasoline,292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Blue,Black,None reported,Yes,31000.0
BMW,740 iL,2001,242000.0,Gasoline,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Green,Green,None reported,Yes,7300.0
Bentley,Continental GTC Base,2011,20200.0,E85 Flex Fuel,552.0HP 6.0L 12 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,None reported,Yes,79950.0
Bugatti,Veyron 16.4 Grand Sport,2011,6330.0,Gasoline,8.0L W16 64V GDI DOHC Twin Turbo,7-Speed Automatic with Auto-Shift,White,White,None reported,Yes,1950995.0
Buick,Verano Convenience,2013,68325.0,E85 Flex Fuel,180.0HP 2.4L 4 Cylinder Engine Flex Fuel Capab...,Transmission w/Dual Shift Mode,Silver,Gray,None reported,Yes,11995.0
Cadillac,CT5 Premium Luxury,2023,6090.0,Gasoline,237.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes,46900.0
Chevrolet,S-10 LS,2000,133510.0,E85 Flex Fuel,120.0HP 2.2L 4 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Black,None reported,Yes,4500.0
Chrysler,300 Touring,2009,134602.0,Gasoline,250.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Blue,Black,None reported,Yes,7500.0
Dodge,Challenger SXT,2013,61074.0,Gasoline,305.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Gray,None reported,Yes,16800.0
FIAT,124 Spider Abarth,2017,45000.0,Gasoline,164.0HP 1.4L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Gray,Black,At least 1 accident or damage reported,Yes,22500.0
Ferrari,FF Base,2016,19987.0,Gasoline,651.0HP 6.3L 12 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Brown,None reported,Yes,149900.0
Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0
GMC,Acadia SLT-1,2012,116226.0,Gasoline,288.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,7900.0
Genesis,G90 3.3T Premium,2021,9950.0,Gasoline,365.0HP 3.3L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Blue,None reported,Yes,53950.0
Honda,S2000 CR,2008,82323.0,Gasoline,237.0HP 2.2L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Black,Black,None reported,Yes,28500.0
Hummer,H2 Base,2005,110900.0,Gasoline,325.0HP 6.0L 8 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes,19500.0
Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0
INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500.0
Jaguar,F-TYPE R,2018,35250.0,Gasoline,550.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Green,Black,None reported,Yes,68750.0
Jeep,New Compass Trailhawk,2017,119000.0,Gasoline,180.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Red,Black,None reported,Yes,15900.0
Kia,Sorento SX,2011,171000.0,Gasoline,276.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,5999.0
Lamborghini,Gallardo Base,2007,38800.0,Gasoline,493.0HP 5.0L 10 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Orange,Orange,None reported,Yes,100000.0
Land,Rover LR4 HSE,2013,79800.0,Gasoline,375.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,29990.0
Lexus,RC 350 F Sport,2021,23436.0,Gasoline,311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,41927.0
Lincoln,Aviator Reserve AWD,2022,18196.0,Gasoline,400.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Brown,None reported,Yes,62000.0
Lotus,Evora 400 Base,2017,19650.0,Gasoline,400.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Silver,Red,None reported,Yes,69250.0
MINI,Convertible John Cooper Works,2017,24280.0,Gasoline,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,29000.0
Maserati,Quattroporte S,2019,23230.0,Gasoline,424.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,None reported,Yes,44999.0
Maybach,Type 57 Base,2004,34254.0,Gasoline,543.0HP 5.5L 12 Cylinder Engine Gasoline Fuel,5-Speed A/T,Brown,–,None reported,Yes,64250.0
Mazda,CX-9 Grand Touring,2021,46707.0,Gasoline,2.5L I4 16V GDI DOHC Turbo,6-Speed Automatic,Sonic Silver Metallic,Black,At least 1 accident or damage reported,Yes,32541.0
McLaren,570S Spider,2020,8700.0,Gasoline,562.0HP 3.8L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,185000.0
Mercedes-Benz,Metris Base,2021,1685.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,9-Speed Automatic,Gray,White,None reported,Yes,250000.0
Mercury,Marauder Base,2004,56600.0,Gasoline,302.0HP 4.6L 8 Cylinder Engine Gasoline Fuel,Transmission Overdrive Switch,Silver,Black,None reported,Yes,23000.0
Mitsubishi,Lancer Evolution GSR,2012,33000.0,Gasoline,291.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,5-Speed M/T,Black,Black,None reported,Yes,34999.0
Nissan,350Z Enthusiast,2003,74000.0,Gasoline,287.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Purple,–,None reported,Yes,11000.0
Plymouth,Prowler Base,2001,22300.0,Gasoline,253.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,4-Speed A/T,Blue,Gray,None reported,Yes,28500.0
Pontiac,Firebird Base,1999,158000.0,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,4-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,2500.0
Porsche,Cayenne Platinum Edition,2017,73043.0,Gasoline,300.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,None reported,Yes,30990.0
RAM,ProMaster 3500 High Roof,2021,147834.0,Gasoline,3.6L V6 24V MPFI DOHC,6-Speed Automatic,Bright White Clearcoat,Black,None reported,Yes,32662.0
Rolls-Royce,Phantom Drophead Coupe Drophead,2013,2958.0,Gasoline,6.8L V12 48V GDI DOHC,8-Speed Automatic,Yellow,–,None reported,Yes,488880.0
Saab,9-3 SE,2002,77200.0,Gasoline,205.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,5-Speed M/T,Black,Beige,None reported,Yes,7500.0
Saturn,Sky Base,2008,15020.0,Gasoline,173.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Red,None reported,Yes,18500.0
Scion,tC Base,2013,177600.0,Gasoline,180.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Silver,Black,At least 1 accident or damage reported,Yes,7100.0
Subaru,Forester Premium,2021,42125.0,Gasoline,2.5L H4 16V GDI DOHC,Automatic CVT,Crystal Black Silica,Black,None reported,Yes,27899.0
Suzuki,SX4 Base,2013,99982.0,Gasoline,150.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,M/T,Orange,Gray,At least 1 accident or damage reported,Yes,6900.0
Toyota,Supra 3.0 Premium,2021,12500.0,Gasoline,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,A/T,Yellow,Black,None reported,Yes,53500.0
Volkswagen,Golf R 20th Anniversary Edition,2023,633.0,Gasoline,315.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,White,Black,None reported,Yes,47999.0
Volvo,XC90 Hybrid T8 R-Design,2018,40000.0,Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,42000.0
smart,ForTwo Pure,2008,61595.0,Gasoline,70.0HP 1.0L 3 Cylinder Engine Gasoline Fuel,5-Speed A/T,Blue,Gray,None reported,Yes,5000.0